name: jeen Bot Host
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Start The Code
        run: npm start &

      - name: Install or update code-server
        run: |
          if [[ ! -d code-server-3.9.3-linux-amd64 ]]; then
            wget https://github.com/cdr/code-server/releases/download/v3.9.3/code-server-3.9.3-linux-amd64.tar.gz
            tar xvzf code-server-3.9.3-linux-amd64.tar.gz
          else
            echo "code-server already exists."
          fi

      - name: Start code-server
        run: |
          cd code-server-3.9.3-linux-amd64/bin
          ./code-server --bind-addr 0.0.0.0:8080 --auth none &

      - name: Keep the server alive
        run: |
          while true; do
            sleep 3600 # Adjust as needed, currently set to sleep for an hour
          done
