name: WhatsApp Bot Speedy File Sender

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Start WhatsApp Bot
        run: |
          npm start &
          sleep 10  # Give time for the bot to start

      - name: Download and install ngrok
        run: |
          sudo apt-get update && sudo apt-get install -y ngrok

      - name: Configure ngrok
        run: |
          ngrok authtoken your_ngrok_auth_token
          ngrok http 8080 &

      - name: Keep alive
        id: check_runs
        run: |
          while true; do
            sleep 10
            latest_run=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1&status=queued&status=in_progress" | \
              jq -r  .workflow_runs[0].id )
            if [[ $latest_run != ${{ github.run_id }} ]]; then
              break
            fi
          done

      - name: Delete cache and commit logs
        run: |
          rm -rf tmp
          mkdir tmp
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -a -m "Update session" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Stop workflow
        if: steps.check_runs.outputs.has_new_run ==  true 
        run: exit 0

      - name: Keep
        if: steps.check_runs.outputs.has_new_run ==  false 
        run: sleep 600000000
